### ISSUE TITLE
Backup logs

### ISSUE THREAD

**Issue by PeterGarlic** [kiorky/db_smart_backup#10]
while log should refer to TOP_BACKUPDIR config var (as also displayed in reports) they are already placed in /var/db_smart_backup/logs/

This error also doesn`t allow log cleanup. A simple script with about 6 month simulation and 2 running db (mongo/postgres) have generated about 400 log files on  /var/db_smart_backup/logs/

**Comment by kiorky** [comment]
Good catch, thx, done
