### ISSUE TITLE
Mongodb sample file name error

### ISSUE THREAD

**Issue by PeterGarlic** [kiorky/db_smart_backup#8]
The configuration file mongodb.conf.sample can make you wasting time because it´s work perfectly with db_smart_backup.sh but when you try to run them with run_dbsmartbackups.sh fails.
After some check to the run_dbsmartbackups.sh script you find that the right configuration file is mongod.conf and you can solve the issue. 

I think that should be better to give the right names to sample files to avoid time wasting.

**Comment by kiorky** [comment]
done, thx !
