### ISSUE TITLE
Script error on postgresql 

### ISSUE THREAD

**Issue by PeterGarlic** [kiorky/db_smart_backup#9]
With an installation of postgres 9.4 on CentOS 7.2 from the PostgreSQL repository the configuration files are not located in /etc/postgres so the expression at line 70 of run_dbsmartbackups.sh fail and also the backup:
 
PORTS=$(egrep -h "^port\s=\s" /etc/postgresql/*/*/post*.conf 2>/dev/null|awk -F= '{print $2}'|awk '{print $1}'|sort -u) 

should be a good idea to change the expression or to add a parameter that define the configuration location.

**Comment by kiorky** [comment]
thx, done
